"""add_credentials_field

Revision ID: 076619c4f740
Revises: c9338f4e7004
Create Date: 2023-08-30 08:15:55.953663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '076619c4f740'
down_revision = 'c9338f4e7004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('company_id', sa.BigInteger(), nullable=False))
    op.add_column('product', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('product', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('product', sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('updated_by', sa.String(), nullable=False))
    op.drop_column('product', 'product_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('product', 'updated_by')
    op.drop_column('product', 'updated_on')
    op.drop_column('product', 'created_by')
    op.drop_column('product', 'created_on')
    op.drop_column('product', 'uuid')
    op.drop_column('product', 'company_id')
    # ### end Alembic commands ###
